### Login oikealla salasanalla
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username":"sms",
    "password":"123"
}

### Login väärällä salasanalla
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username":"sms",
    "password":"1234"
}
